# Generated by Django 4.0.4 on 2024-07-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_idea_content_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='content_generated',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
